### ISSUE TITLE
Dynamo only provides power in direction of positive Z

### ISSUE THREAD

**Issue by OneTwoMint** [LordGrimmauld/createintegration#1]
Pretty much as stated in the title. The dynamo, when given rotational power, only passes the FE generated on to blocks in the direction of positive Z. It is fairly well demonstrated in this screenshot. Around each dynamo is a Refined Storage controller on each side that doesn't have a motor. The blue ones are the ones being powered. Latest version of both Create(0.2.3) and Create Integration(0.1.3). Forge is 1.14.4 - 28.2.0
![2020-05-10_21 12 24](https://user-images.githubusercontent.com/38229099/81518771-bbe94280-9304-11ea-83ba-10ad1b9a9699.png)

**Comment by LordGrimmauld** [comment]
oh damn it. Yes possible. i know where it comes from. I will fix this right now. Thanks for reporting.

**Comment by LordGrimmauld** [comment]
Ok this should be fixed in the release i published a second ago. i had the line responsible for the direction messed up. I will close this issue tomorrow when either no new complaints about this issue come in or you say it works. Thanks for reporting again, i will remember to test my blocks in all directions from now on  :+1:

**Comment by OneTwoMint** [comment]
As far as I can tell, the issue is fixed! Thanks!
![2020-05-11_11 33 00](https://user-images.githubusercontent.com/38229099/81586538-45d3f280-937b-11ea-92bb-5cfd6d44a09a.png)

**Comment by CaveJohnson376** [comment]
yay, first issue!
